export const COLORS = {
  primary: "#6c5dd3",
  primaryDark: "#5647b8",
  primaryLight: "#e4e1fb",
  secondary: "#ffc93c",
  secondaryLight: "#fff3d1",
  accentMint: "#2fd3a6",
  accentMintLight: "#dff9ef",
  accentCoral: "#ff6584",
  accentCoralLight: "#ffe3e8",
  background: "#ffffff",
  surface: "#f7f7fb",
  textPrimary: "#16151c",
  textSecondary: "#8c8c9c",
  border: "#ececf4",
  success: "#2fd3a6",
  warning: "#ffc93c",
  danger: "#ff6584",
} as const;
